#!/bin/sh

USER=fullstacksjs

if [ -z "$1" ]; then
  echo "Error: please specify version"
  # exit 1
fi

docker build --tag $USER/lerna:15.12-slim -f ./lerna/Dockerfile .
docker build --tag $USER/lerna:14.16-slim -f ./lerna/Dockerfile.lts .
